version: '3.9'
services:
  embedbot:
    container_name: EmbedBot
    pull_policy: build
    build: .
    volumes:
      - type: bind
        source: /var/log/brackeysbot/embedbot
        target: /app/logs
      - type: bind
        source: /etc/brackeysbot/embedbot
        target: /app/data
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
